import React from 'react';
import { 
  FileText, 
  AlertTriangle, 
  Download, 
  Printer, 
  Sparkles, 
  CheckCircle2, 
  MapPin, 
  Clock, 
  Compass, 
  UserCheck, 
  Flame, 
  ShieldCheck 
} from 'lucide-react';
import { useMission } from '../context/MissionContext';
import { PageHeader } from '../components/common/PageHeader';
import { Button } from '../components/ui/Button';

export function ReportsPage() {
  const { activeMission, robots, detections } = useMission();

  const victimsCount = detections.filter((d) => d.type === 'Victim' && d.status !== 'DISMISSED').length;
  const hazardsCount = detections.filter((d) => d.type !== 'Victim' && d.type !== 'Emergency Exit' && d.status !== 'DISMISSED').length;

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      <PageHeader
        title="AI Mission Intelligence Report"
        subtitle="Post-sortie telemetry analysis, victim triage priority, and ingress pathfinding"
        badge={
          <span className="px-2.5 py-1 rounded-full bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 font-mono text-xs border border-cyan-500/30 font-semibold">
            PREVIEW DRAFT
          </span>
        }
        action={
          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="md"
              onClick={() => window.print()}
              className="gap-2 font-mono text-xs"
            >
              <Printer className="w-3.5 h-3.5" />
              Print / Save PDF
            </Button>
          </div>
        }
      />

      {/* Mandatory AI Recommendation Warning Banner */}
      <div className="rounded-xl border border-amber-500/40 bg-amber-500/10 p-4 text-amber-800 dark:text-amber-300 flex items-start gap-3">
        <AlertTriangle className="w-5 h-5 shrink-0 mt-0.5 text-amber-600 dark:text-amber-400" />
        <div className="space-y-1">
          <div className="font-bold text-sm font-mono tracking-wide">
            AI Recommendation — Human decision required
          </div>
          <p className="text-xs text-amber-700 dark:text-amber-400/90 leading-relaxed font-sans">
            Autonomous path planning and victim triage orders generated by heuristic intelligence are advisory only.
            The Incident Commander must verify structural integrity, atmospheric gas thresholds, and personnel safety before authorizing extraction teams.
          </p>
        </div>
      </div>

      {/* Mission Report Paper Container */}
      <div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900/90 p-6 sm:p-8 shadow-sm dark:shadow-2xl space-y-8 font-sans">
        {/* Document Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-6 border-b border-slate-200 dark:border-slate-800 gap-4">
          <div>
            <div className="text-xs font-mono font-bold text-cyan-600 dark:text-cyan-400 uppercase tracking-wider">
              RESCUEHIVE AUTONOMOUS SYNTHESIS
            </div>
            <h2 className="text-2xl font-bold font-mono text-slate-900 dark:text-white mt-1">
              {activeMission?.name || 'Operation Cerberus'}
            </h2>
            <p className="text-xs text-slate-500 mt-1 font-mono">
              Mission Code: {activeMission?.code} • Commander: {activeMission?.leadCommander}
            </p>
          </div>

          <div className="text-right font-mono text-xs text-slate-500">
            <div>Generated: {new Date().toLocaleDateString()} {new Date().toLocaleTimeString()}</div>
            <div>Classification: TACTICAL RESTRICTED</div>
          </div>
        </div>

        {/* 1. Mission Summary Grid */}
        <div className="space-y-3">
          <h3 className="text-xs font-mono font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
            1. Sortie Executive Summary
          </h3>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 font-mono text-xs">
            <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-950/60 border border-slate-200 dark:border-slate-800">
              <span className="text-slate-400 text-[10px] uppercase block">Explored Area</span>
              <span className="text-lg font-bold text-slate-900 dark:text-white mt-1 block">
                {activeMission?.exploredAreaPercent}% ({activeMission?.exploredAreaSqM?.toLocaleString()} m²)
              </span>
            </div>

            <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-950/60 border border-slate-200 dark:border-slate-800">
              <span className="text-slate-400 text-[10px] uppercase block">Mission Duration</span>
              <span className="text-lg font-bold text-slate-900 dark:text-white mt-1 block">
                {activeMission?.duration}
              </span>
            </div>

            <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-950/60 border border-slate-200 dark:border-slate-800">
              <span className="text-slate-400 text-[10px] uppercase block">Victims Detected</span>
              <span className="text-lg font-bold text-rose-500 mt-1 block">
                {victimsCount} Flagged
              </span>
            </div>

            <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-slate-950/60 border border-slate-200 dark:border-slate-800">
              <span className="text-slate-400 text-[10px] uppercase block">Hazards Identified</span>
              <span className="text-lg font-bold text-amber-500 mt-1 block">
                {hazardsCount} Flagged
              </span>
            </div>
          </div>
        </div>

        {/* 2. Recommended Rescue Order */}
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <h3 className="text-xs font-mono font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
              2. Recommended Rescue & Extraction Triage Order
            </h3>
            <span className="text-[11px] font-mono text-amber-500">
              AI Priority Ranking
            </span>
          </div>

          <div className="space-y-3">
            <div className="p-4 rounded-xl border border-rose-500/30 bg-rose-500/5 space-y-2">
              <div className="flex items-center justify-between">
                <span className="px-2 py-0.5 rounded bg-rose-500 text-white font-mono font-bold text-xs">
                  PRIORITY 1 (CRITICAL)
                </span>
                <span className="font-mono text-xs text-rose-500 font-semibold">
                  DET-1001 • Sector 4B (Collapsed Stairwell)
                </span>
              </div>
              <p className="text-sm font-semibold text-slate-900 dark:text-white">
                Survivor in Basement Cavity beneath pre-stressed slab
              </p>
              <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
                Thermal respirations confirmed by Robot Alpha. Structural movement risk high due to localized fire 12m away in Basement Electrical Hub. Immediate hydraulic shoring extraction recommended.
              </p>
            </div>

            <div className="p-4 rounded-xl border border-amber-500/30 bg-amber-500/5 space-y-2">
              <div className="flex items-center justify-between">
                <span className="px-2 py-0.5 rounded bg-amber-500 text-slate-950 font-mono font-bold text-xs">
                  PRIORITY 2 (HIGH)
                </span>
                <span className="font-mono text-xs text-amber-500 font-semibold">
                  DET-1005 • Sector 4C (Office 102)
                </span>
              </div>
              <p className="text-sm font-semibold text-slate-900 dark:text-white">
                Trapped Survivor behind Drywall Partition
              </p>
              <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
                Acoustic triangulations by Robot Charlie confirm conscious survivor. Low atmospheric hazard. Recommend manual breach via Corridor West once heavy beam debris is stabilized.
              </p>
            </div>
          </div>
        </div>

        {/* 3. Recommended Safe Route */}
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <h3 className="text-xs font-mono font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
              3. Recommended Safe Ingress / Egress Route
            </h3>
            <span className="text-[11px] font-mono text-emerald-500">
              Hazard-Avoidance Optimization
            </span>
          </div>

          <div className="p-4 rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950/50 space-y-3 font-mono text-xs">
            <div className="flex items-center gap-2 text-emerald-600 dark:text-emerald-400 font-bold">
              <CheckCircle2 className="w-4 h-4" />
              <span>OPTIMAL VECTOR: REAR EMERGENCY ACCESS (WAYPOINT GREEN-ALPHA)</span>
            </div>

            <ol className="list-decimal list-inside space-y-1.5 text-slate-700 dark:text-slate-300 pl-1">
              <li>Enter through Rear Emergency Exit Door (DET-1006, Sector 4A rear perimeter) — Confirmed unobstructed.</li>
              <li>Traverse West Service Gallery avoiding Sector 4B Electrical Hub due to 480°C open flame (DET-1002).</li>
              <li>Maintain 15-meter safety radius from LPG Gas Cylinder hazard (DET-1003) at coordinates (71.5, 52.0).</li>
              <li>Establish secondary casualty collection point at Staging Zone Bravo.</li>
            </ol>
          </div>
        </div>

        {/* Commander Signature Sign-off */}
        <div className="pt-6 border-t border-slate-200 dark:border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-4 font-mono text-xs text-slate-500">
          <div>
            <span>Status: Awaiting Incident Commander Final Approval</span>
          </div>
          <div className="border-b border-dashed border-slate-400 w-48 text-right pb-1">
            Sign: Cmdr. S. Vance
          </div>
        </div>
      </div>
    </div>
  );
}
